### ISSUE TITLE
Database Table for Motorcycle information/Data Dictionary

### ISSUE THREAD

**Issue by JordanXA** [JordanXA/business-analysis#7]

**Comment by lwilcox248** [comment]
Data Dictionary (as of right no
[Data Dictionary Template.xlsx](https://github.com/JordanXA/business-analysis/files/7179552/Data.Dictionary.Template.xlsx)
w)

**Comment by lwilcox248** [comment]
Updated Data Dictionary
[Data Dictionary Template.xlsx](https://github.com/JordanXA/business-analysis/files/7212455/Data.Dictionary.Template.xlsx)
